Repository AY2021S2-CS2103-T14-3/tp, pull requests merged in 2021-03, with the labels that each got.

#29 Info about me: yutingzou.md
  docs/team/yutingzou.md
Labels: documentation, priority.Medium, type.Task

#39 Updated personal portfolio in jared98lyj.md
  docs/team/jared98lyj.md
  docs/team/johndoe.md
Labels: documentation, priority.Low

#13 Update User Guide with add_tutor and list_tutors commands
  docs/UserGuide.md
Labels: documentation, priority.High, type.Task

#44 Add About Me: Koh Vinleon (glatiuden)
  docs/team/glatiuden.md
Labels: documentation, priority.Medium

#37 Updated developer guide to include NFRs.
  docs/DeveloperGuide.md
Labels: documentation, priority.Low

#2 User Guide: Update List Appointments
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/team/jared98lyj.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation, priority.High

#35 Add about me personal portfolio for Kingsley Kuan
  docs/AboutUs.md
  docs/images/glatiuden.png
  docs/team/kingsleykuan.md
Labels: documentation, priority.Medium, type.Task

#10 UG: Add 'view appointment, delete appointment' for features
  docs/UserGuide.md
Labels: documentation, priority.High, type.Task

#11 Developer Guide: User Stories, Use Cases and Class Diagrams
  docs/DeveloperGuide.md
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation, priority.High, type.Task

#32 Info about me: Winniehyx.md
  docs/team/Winniehyx.md
Labels: documentation, priority.Medium, type.Task

#36 Updated user guide to include view_tutor command
  docs/UserGuide.md
Labels: documentation, priority.Low, type.Task

#5 Developer Guide: Update Design (Architecture, Logic), Use Cases (List Appointments) Section
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/Ui.png
  docs/team/Winniehyx.md
  docs/team/jared98lyj.md
Labels: documentation, priority.High

#48 Fix User Guide by moving features to bottom of feature section
  docs/UserGuide.md
Labels: documentation, severity.High, type.Bug

#50 Fix User Guide and Developer Guide formatting
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/Winniehyx.md
  docs/team/yutingzou.md
Labels: documentation, severity.Medium, type.Bug

#51 Fix DG user stories formatting
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: documentation, severity.High, type.Bug

#62 Add Tag Exceptions
  src/main/java/seedu/address/model/tag/exceptions/DuplicateTagException.java
  src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
Labels: priority.Medium, type.Task

#65 Add TagList.java and add method: isSameTag()
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagList.java
Labels: priority.High, type.Task

#55 Add TutorSubject and Subject classes, modify Person to contain List of TutorSubjects
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/subject/SubjectExperience.java
  src/main/java/seedu/address/model/subject/SubjectLevel.java
  src/main/java/seedu/address/model/subject/SubjectName.java
  src/main/java/seedu/address/model/subject/SubjectQualification.java
  src/main/java/seedu/address/model/subject/SubjectRate.java
  src/main/java/seedu/address/model/subject/TutorSubject.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Task

#64 Add and modify classes in Logic Packages
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/FindAppointmentCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/TutorTrackerParserTest.java
Labels: priority.High, type.Task

#79 Cleaned up appointment class.
  src/main/java/seedu/address/model/Appointment.java
Labels: enhancement, priority.High, type.Task

#9 Add AppointmentList
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
Labels: priority.High, type.Task

#85 Added add-appointment delete-appointment command
  src/main/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
Labels: enhancement, priority.High, type.Task

#80 Add SubjectList and exceptions
  src/main/java/seedu/address/model/subject/SubjectList.java
  src/main/java/seedu/address/model/subject/exceptions/DuplicateSubjectException.java
  src/main/java/seedu/address/model/subject/exceptions/SubjectNotFoundException.java
  src/main/java/seedu/address/model/tag/TagList.java
Labels: priority.High, type.Task

#83 Add list_tutors command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Task

#86 Add command view_tutor
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High, type.Task

#88 Add add_tutor, delete_tutor and storage for tutor
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/subject/SubjectQualification.java
  src/main/java/seedu/address/model/subject/TutorSubject.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorSubject.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: enhancement, priority.High, type.Enhancement

#96 Add find_appointment, list_appointment and view_appointment command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/ViewAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/FindAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/ViewAppointmentCommandParser.java
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAppointmentBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
  src/main/java/seedu/address/model/appointment/DateViewPredicate.java
  src/main/java/seedu/address/model/appointment/EmailPredicate.java
  src/main/java/seedu/address/model/appointment/ViewAppointmentPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/AppointmentListPanel.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Task

#98 Update edit_tutor command and refactor to use SubjectList
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorSubject.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Task

#94 Add parsing of add_appointment command
  src/main/java/seedu/address/logic/commands/appointmentcommands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
Labels: priority.High, type.Bug

#99 Update user guide to modify appointment-related command
  docs/UserGuide.md
Labels: priority.Medium

#91 Update Ui to display subjects of each tutor
  docs/UserGuide.md
  src/main/java/seedu/address/ui/TutorCard.java
  src/main/resources/view/TutorListCard.fxml
Labels: priority.Medium, type.Enhancement

#97 Add edit_appointment parser and command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointmentparser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Task

#101 Added Storage features for AppointmentBook and correponding Json storage helper classes
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/AppointmentBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAppointmentBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAppointmentBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement, priority.High, type.Task

#107 Fix appointment storage by implementing incomplete methods and fixing deserialization
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/StorageManager.java
Labels: priority.High, severity.High, type.Bug

#104 Update UG, Ui and minor bug fix for ViewAppointmentCommandParser
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/appointmentparser/ViewAppointmentCommandParser.java
  src/main/java/seedu/address/ui/ResultBarFooter.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: severity.Medium, type.Bug

#108 Update AppointmentDateTime
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
Labels: priority.Medium, type.Bug

#110 Modify TutorCard
  src/main/java/seedu/address/ui/TutorCard.java
  src/main/resources/view/TutorListCard.fxml
Labels: type.Enhancement

#113 Fix user guide with edit commands along with other fixes
  docs/UserGuide.md
Labels: severity.Medium, type.Bug

#114 Fix majority of unit tests for v1.2
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, severity.High, type.Bug

#115 Modify view_tutor
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/ViewTutorPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TutorCard.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: priority.High, type.Bug

#117 Fix minor unit test errors by removing clear command test and fixing checkstyle errors
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jared98lyj.md
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/TutorTrackerParserTest.java
Labels: severity.Low, type.Bug

#119 Branch appointment class
  src/main/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
  src/main/java/seedu/address/model/appointment/DateViewPredicate.java
  src/main/java/seedu/address/model/appointment/NamePredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/resources/view/AppointmentListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/FindAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/ViewAppointmentCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/appointment/AppointmentBookTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: enhancement, priority.High, type.Task

#124 Added feature: favourite, unfavourite, list all favourites
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/ListFavouriteCommand.java
  src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/UnfavouriteCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/ViewTutorPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/TutorCard.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: documentation, enhancement, type.Task

#121 Update FindAppointmentCommand and new JUnit Test Cases
  src/main/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/appointmentparser/FindAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/DateViewPredicate.java
  src/main/java/seedu/address/model/appointment/NamePredicate.java
  src/main/java/seedu/address/model/appointment/ViewAppointmentPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/FindAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/appointmentparser/FindAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentDateTimeTest.java
  src/test/java/seedu/address/model/appointment/DateViewPredicateTest.java
  src/test/java/seedu/address/model/appointment/NamePredicateTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: severity.High, type.Bug

#122 Update DG: Brief implementation description of Gradebook
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#126 Add Grade and GradeList
  build.gradle
  src/main/java/seedu/address/model/grade/Grade.java
  src/main/java/seedu/address/model/grade/GradeList.java
  src/main/java/seedu/address/model/grade/exceptions/DuplicateGradeException.java
  src/main/java/seedu/address/model/grade/exceptions/GradeNotFoundException.java
Labels: priority.High, type.Task

#130 Update DG: Brief implementation description of Favourites and Notes
  docs/DeveloperGuide.md
Labels: documentation

#136 Update DG: Brief implementation description of Schedule and Reminder
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#137 Update Developer Guide with Filter function
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#140 Add GradeBook skeleton
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/gradecommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/parser/gradeparser/AddGradeCommandParser.java
  src/main/java/seedu/address/model/GradeBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyGradeBook.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/grade/GradeList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/GradeBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedGrade.java
  src/main/java/seedu/address/storage/JsonGradeBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableGradeBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/FindAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/ViewAppointmentCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/GradeBookBuilder.java
  src/test/java/seedu/address/testutil/GradeBuilder.java
  src/test/java/seedu/address/testutil/TypicalGrades.java
Labels: priority.High, type.Enhancement, type.Task

#138 Add Feature - Budget (Complete)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/budgetcommands/AddBudgetCommand.java
  src/main/java/seedu/address/logic/commands/budgetcommands/DeleteBudgetCommand.java
  src/main/java/seedu/address/logic/commands/budgetcommands/EditBudgetCommand.java
  src/main/java/seedu/address/logic/commands/budgetcommands/ViewBudgetCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/budgetparser/AddBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/budgetparser/DeleteBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/budgetparser/EditBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/budgetparser/ViewBudgetCommandParser.java
  src/main/java/seedu/address/model/BudgetBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyBudgetBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/GetAddressBook.java
  src/main/java/seedu/address/model/budget/GetAppointmentBook.java
  src/main/java/seedu/address/model/budget/GetAppointmentCost.java
  src/main/java/seedu/address/model/budget/GetTotalCost.java
  src/main/java/seedu/address/model/budget/NameSubjectRate.java
  src/main/java/seedu/address/storage/BudgetBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/FindAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/ViewAppointmentCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalBudgets.java
Labels: enhancement, priority.High, type.Enhancement, type.Task

#142 Add Schedule Feature (Partial)
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/schedulecommands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/scheduleparser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/scheduleparser/DeleteScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/model/schedule/Description.java
  src/main/java/seedu/address/model/schedule/ReadOnlyScheduleTracker.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/ScheduleList.java
  src/main/java/seedu/address/model/schedule/ScheduleTracker.java
  src/main/java/seedu/address/model/schedule/Title.java
  src/main/java/seedu/address/model/schedule/exceptions/DuplicateScheduleException.java
  src/main/java/seedu/address/model/schedule/exceptions/ScheduleNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement, type.Task

#152 Add skeleton for Tutor Filter feature (Complete)
  src/main/java/seedu/address/logic/commands/filtercommands/AddPersonFilterCommand.java
  src/main/java/seedu/address/logic/commands/filtercommands/DeletePersonFilterCommand.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/filterparser/AddPersonFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/filterparser/DeletePersonFilterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/filter/NameFilter.java
  src/main/java/seedu/address/model/filter/PersonFilter.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/AddPersonFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/DeletePersonFilterCommandTest.java
  src/test/java/seedu/address/logic/parser/filterparser/AddPersonFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/filterparser/DeletePersonFilterCommandParserTest.java
  src/test/java/seedu/address/model/filter/NameFilterTest.java
  src/test/java/seedu/address/model/filter/PersonFilterTest.java
Labels: priority.High, type.Task

#144 Add AddGrade, EditGrade, DeleteGrade and ListGrade commands
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/gradecommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradecommands/DeleteGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradecommands/EditGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradecommands/ListGradeCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/gradeparser/AddGradeCommandParser.java
  src/main/java/seedu/address/logic/parser/gradeparser/DeleteGradeCommandParser.java
  src/main/java/seedu/address/logic/parser/gradeparser/EditGradeCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/grade/Grade.java
  src/main/java/seedu/address/model/grade/GradeEnum.java
  src/main/java/seedu/address/model/grade/GradedItem.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGrade.java
  src/main/java/seedu/address/storage/JsonGradeBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableGradeBook.java
  src/main/java/seedu/address/ui/GradeCard.java
  src/main/java/seedu/address/ui/GradeListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/gradebook_icon.png
  src/main/resources/view/GradeListCard.fxml
  src/main/resources/view/GradeListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/GradeBuilder.java
  src/test/java/seedu/address/testutil/TypicalGrades.java
Labels: priority.High, type.Enhancement

#156 Removed irrelevant information from DG
  docs/DeveloperGuide.md
Labels: documentation

#159 Add EditScheduleCommand and ListScheduleCommand
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/schedulecommands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/ListScheduleCommand.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/scheduleparser/EditScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#158 Add supported filterable attributes to Tutor Filter feature (Complete)
  src/main/java/seedu/address/logic/parser/filterparser/AddPersonFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/filterparser/DeletePersonFilterCommandParser.java
  src/main/java/seedu/address/model/filter/AddressFilter.java
  src/main/java/seedu/address/model/filter/EmailFilter.java
  src/main/java/seedu/address/model/filter/GenderFilter.java
  src/main/java/seedu/address/model/filter/PersonFilter.java
  src/main/java/seedu/address/model/filter/PhoneFilter.java
  src/main/java/seedu/address/model/filter/SubjectExperienceFilter.java
  src/main/java/seedu/address/model/filter/SubjectLevelFilter.java
  src/main/java/seedu/address/model/filter/SubjectNameFilter.java
  src/main/java/seedu/address/model/filter/SubjectQualificationFilter.java
  src/main/java/seedu/address/model/filter/SubjectRateFilter.java
  src/test/java/seedu/address/logic/commands/filtercommands/AddPersonFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/DeletePersonFilterCommandTest.java
  src/test/java/seedu/address/logic/parser/filterparser/AddPersonFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/filterparser/DeletePersonFilterCommandParserTest.java
  src/test/java/seedu/address/model/filter/PersonFilterTest.java
Labels: priority.High, type.Enhancement

#168 Add TimeTable GUI
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/eventcommands/ViewTimeTableCommand.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/event/CurrentWeekPredicate.java
  src/main/java/seedu/address/model/event/EventModel.java
  src/main/java/seedu/address/model/schedule/Description.java
  src/main/java/seedu/address/model/schedule/ScheduleTracker.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/timetablepanel/AppointmentSlot.java
  src/main/java/seedu/address/ui/timetablepanel/DisplayDateSlot.java
  src/main/java/seedu/address/ui/timetablepanel/DisplayTimeSlot.java
  src/main/java/seedu/address/ui/timetablepanel/ScheduleSlot.java
  src/main/java/seedu/address/ui/timetablepanel/SlotContainer.java
  src/main/java/seedu/address/ui/timetablepanel/TimeTablePanel.java
  src/main/java/seedu/address/ui/timetablepanel/TimeTableWindow.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/timetablepanel/AppointmentSlot.fxml
  src/main/resources/view/timetablepanel/DisplayDateSlot.fxml
  src/main/resources/view/timetablepanel/DisplayTimeSlot.fxml
  src/main/resources/view/timetablepanel/ScheduleSlot.fxml
  src/main/resources/view/timetablepanel/TimeTablePanel.fxml
  src/main/resources/view/timetablepanel/TimeTableStyle.css
  src/main/resources/view/timetablepanel/TimeTableWindow.fxml
Labels: priority.High, type.Enhancement, type.Task

#169 Improved code logic for add_appointment and delete_tutor
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, type.Enhancement, type.Task

#165 Add Appointment Filter feature (Complete)
  src/main/java/seedu/address/logic/commands/filtercommands/AddAppointmentFilterCommand.java
  src/main/java/seedu/address/logic/commands/filtercommands/DeleteAppointmentFilterCommand.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/filterparser/AddAppointmentFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/filterparser/DeleteAppointmentFilterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/main/java/seedu/address/model/filter/AppointmentDateTimeFilter.java
  src/main/java/seedu/address/model/filter/AppointmentFilter.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement

#170 Add GUI for Tutor Filter and Appointment Filter features
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/filter/AddressFilter.java
  src/main/java/seedu/address/model/filter/AppointmentDateTimeFilter.java
  src/main/java/seedu/address/model/filter/AppointmentFilter.java
  src/main/java/seedu/address/model/filter/EmailFilter.java
  src/main/java/seedu/address/model/filter/GenderFilter.java
  src/main/java/seedu/address/model/filter/NameFilter.java
  src/main/java/seedu/address/model/filter/PersonFilter.java
  src/main/java/seedu/address/model/filter/PhoneFilter.java
  src/main/java/seedu/address/model/filter/SubjectExperienceFilter.java
  src/main/java/seedu/address/model/filter/SubjectLevelFilter.java
  src/main/java/seedu/address/model/filter/SubjectNameFilter.java
  src/main/java/seedu/address/model/filter/SubjectQualificationFilter.java
  src/main/java/seedu/address/model/filter/SubjectRateFilter.java
  src/main/java/seedu/address/ui/FilterCard.java
  src/main/java/seedu/address/ui/FilterList.java
  src/main/java/seedu/address/ui/FiltersPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FilterCard.fxml
  src/main/resources/view/FilterList.fxml
  src/main/resources/view/FiltersPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement

#171 Fixed all bugs in issue #143 and refactoring of tutor and favourite into packages
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/favouritecommands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/favouritecommands/ListFavouriteCommand.java
  src/main/java/seedu/address/logic/commands/favouritecommands/UnfavouriteCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/AddCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/EditCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/FindCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/ListCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/favouriteparser/FavouriteCommandParser.java
  src/main/java/seedu/address/logic/parser/favouriteparser/UnfavouriteCommandParser.java
  src/main/java/seedu/address/logic/parser/tutorparser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/tutorparser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/tutorparser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/tutorparser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/tutorparser/ViewCommandParser.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TutorTrackerParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: severity.Medium, type.Bug

#167 Added Notes feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/tutorcommands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/tutorparser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/tutorparser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Notes.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/TutorCard.java
  src/main/java/seedu/address/ui/TutorNotesField.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TutorListCard.fxml
  src/main/resources/view/TutorNotesField.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#162 Edited Model class diagram and storage class diagram
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#177 Update SubjectName and GradedItem to make them case-insensitive
  src/main/java/seedu/address/model/grade/GradedItem.java
  src/main/java/seedu/address/model/subject/SubjectName.java
Labels: priority.Medium, type.Enhancement

#172 Add Schedule Storage Capability & Unit Test for Schedule Model
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/schedulecommands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/scheduleparser/AddScheduleCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/common/Description.java
  src/main/java/seedu/address/model/common/Title.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/ScheduleTracker.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/java/seedu/address/storage/JsonScheduleTrackerStorage.java
  src/main/java/seedu/address/storage/JsonSerializableScheduleTracker.java
  src/main/java/seedu/address/storage/ScheduleTrackerStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/FindAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/ViewAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/AddPersonFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/DeletePersonFilterCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/schedule/DescriptionTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/TitleTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/ModelManagerBuilder.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/ScheduleTrackerBuilder.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High, type.Task

#173 Edit user guide
  docs/UserGuide.md
Labels: documentation

#181 Add Schedule Ui
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/eventcommands/ViewEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/eventparser/ViewEventCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/DateRangePredicate.java
  src/main/java/seedu/address/model/event/EventList.java
  src/main/java/seedu/address/model/event/EventTracker.java
  src/main/java/seedu/address/model/schedule/ScheduleDateViewPredicate.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/schedulepanel/ScheduleCard.java
  src/main/java/seedu/address/ui/schedulepanel/ScheduleListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TabStyle.css
  src/main/resources/view/schedulepanel/ScheduleListCard.fxml
  src/main/resources/view/schedulepanel/ScheduleListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#190 Updated user guide for Budget with examples and example output.
  docs/UserGuide.md
Labels: documentation, priority.Low

#188 Update UserGuide on Grade features
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/gradecommands/DeleteGradeCommand.java
Labels: documentation, priority.High

#185 Add skeleton codes for Reminder
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/remindercommands/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/EditReminderCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/ListReminderCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/reminderparser/AddReminderCommandParser.java
  src/main/java/seedu/address/logic/parser/reminderparser/DeleteReminderCommandParser.java
  src/main/java/seedu/address/logic/parser/reminderparser/EditReminderCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventTracker.java
  src/main/java/seedu/address/model/reminder/ReadOnlyReminderTracker.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderDate.java
  src/main/java/seedu/address/model/reminder/ReminderList.java
  src/main/java/seedu/address/model/reminder/ReminderTracker.java
  src/main/java/seedu/address/model/reminder/exceptions/DuplicateReminderException.java
  src/main/java/seedu/address/model/reminder/exceptions/ReminderNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/reminderpanel/ReminderCard.java
  src/main/java/seedu/address/ui/reminderpanel/ReminderListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/reminderpanel/ReminderListCard.fxml
  src/main/resources/view/reminderpanel/ReminderListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#187 Edit UG for add_tutor,edit_tutor and export
  docs/UserGuide.md
  export/Alex_Yeoh
Labels: documentation

#201 Add Schedule Ui
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/reminderpanel/ReminderCard.java
  src/main/java/seedu/address/ui/reminderpanel/ReminderListPanel.java
  src/main/resources/images/book_icon.png
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/reminderpanel/ReminderListCard.fxml
  src/main/resources/view/reminderpanel/ReminderWindowStyle.css
Labels: priority.High, type.Enhancement, type.Task

#200 Update User Guide with Tutor and Appointment Filter features
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task

#202 Implemented junit tests for favourite, export and notes commands
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/favouritecommands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/favouritecommands/UnfavouriteCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/EditNoteCommand.java
  src/main/java/seedu/address/logic/parser/tutorparser/DeleteNoteCommandParser.java
  src/test/data/JsonSerializableTutorBookTest/typicalTutorTutorBook.json
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/favouritecommands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/favouritecommands/ListFavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/favouritecommands/UnfavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/EditNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/EditTutorDescriptorTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/ListNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/TutorTrackerParserTest.java
  src/test/java/seedu/address/logic/parser/favouriteparser/FavouriteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/favouriteparser/UnfavouriteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/tutorparser/AddNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/tutorparser/DeleteNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/tutorparser/EditNoteCommandParserTest.java
  src/test/java/seedu/address/model/tutor/NotesTest.java
  src/test/java/seedu/address/testutil/EditTutorDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TutorBuilder.java
  src/test/java/seedu/address/testutil/TypicalModel.java
  src/test/java/seedu/address/testutil/TypicalTutors.java
Labels: enhancement

#205 Fix bugs and inconsistencies in User Guide
  docs/UserGuide.md
Labels: severity.Medium, type.Bug

#209 added check for editing of notes using edit_tutor command
  src/main/java/seedu/address/logic/commands/tutorcommands/AddCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/EditCommand.java
  src/test/java/seedu/address/logic/commands/tutorcommands/EditCommandTest.java
Labels: enhancement

#212 Update UG with schedule and reminder
  docs/UserGuide.md
Labels: documentation, type.Task

#213 Improve Grade and add isSameGrade() method
  src/main/java/seedu/address/logic/commands/gradecommands/EditGradeCommand.java
  src/main/java/seedu/address/model/grade/Grade.java
  src/main/java/seedu/address/model/grade/GradeList.java
Labels: documentation, priority.High

#211 Edited user guide
  docs/UserGuide.md
Labels: documentation

#215 added useful message_usages for favourite, notes and export commands
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/favouritecommands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/favouritecommands/UnfavouriteCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/EditNoteCommand.java
Labels: documentation

#217 Update landing page as well as UI image
  docs/images/Ui.png
  docs/index.md
Labels: documentation, type.Enhancement

#218 Improve TutorCard to show multiple subjects
  src/main/java/seedu/address/ui/TutorCard.java
  src/main/resources/view/TutorListCard.fxml
Labels: priority.High, type.Bug
