Repository AY2021S2-CS2103-T14-3/tp, pull requests merged in 2021-04, with the labels that each got.

#223 Fix bug in view_schedule and timetable GUI
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/scheduleparser/ViewScheduleCommandParser.java
  src/main/java/seedu/address/ui/timetablepanel/TimeTablePanel.java
Labels: severity.High, type.Bug

#228 Bug fixes for Schedule, Reminder and Event
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/remindercommands/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/EditReminderCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/scheduleparser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/scheduleparser/EditScheduleCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventList.java
  src/main/java/seedu/address/model/event/EventTracker.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderDate.java
  src/main/java/seedu/address/model/reminder/ReminderTracker.java
  src/main/java/seedu/address/model/schedule/ScheduleDateViewPredicate.java
  src/main/java/seedu/address/model/schedule/ScheduleTracker.java
  src/main/java/seedu/address/ui/schedulepanel/ScheduleCard.java
  src/main/java/seedu/address/ui/schedulepanel/ScheduleListPanel.java
  src/main/java/seedu/address/ui/timetablepanel/AppointmentSlot.java
  src/main/java/seedu/address/ui/timetablepanel/DisplayDateSlot.java
  src/main/java/seedu/address/ui/timetablepanel/ScheduleSlot.java
  src/main/java/seedu/address/ui/timetablepanel/SlotContainer.java
  src/main/java/seedu/address/ui/timetablepanel/TimeTablePanel.java
  src/main/resources/view/reminderpanel/ReminderWindowStyle.css
Labels: severity.High, severity.Medium, type.Bug

#229 Bug Fix on Timetable Ui
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/eventcommands/ViewTimeTableCommand.java
  src/main/java/seedu/address/logic/parser/TutorTrackerParser.java
  src/main/java/seedu/address/logic/parser/eventparser/ViewTimeTableCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/CurrentWeekPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/timetablepanel/TimeTablePanel.java
  src/main/java/seedu/address/ui/timetablepanel/TimeTableWindow.java
  src/test/java/seedu/address/logic/commands/tutorcommands/AddCommandTest.java
Labels: severity.Medium, type.Bug

#230 Branch appointment test
  docs/UserGuide.md
  export/Alex_Yeoh
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/tutorcommands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TutorBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
  src/test/data/JsonSerializableTutorBookTest/typicalTutorTutorBook.json
  src/test/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/appointmentparser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/appointmentparser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/appointmentparser/EditAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentListTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/testutil/TypicalTutors.java
Labels: severity.High, type.Bug, type.Task

#231 Update version number in MainApp to v1.3.1
  src/main/java/seedu/address/MainApp.java
Labels: priority.Low, type.Enhancement

#234 Fix bugs and add JUnit tests for Grade and GradeBook
  src/main/java/seedu/address/logic/commands/gradecommands/DeleteGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradecommands/EditGradeCommand.java
  src/main/java/seedu/address/logic/parser/gradeparser/AddGradeCommandParser.java
  src/main/java/seedu/address/logic/parser/gradeparser/EditGradeCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedGrade.java
  src/test/data/JsonGradeBookStorageTest/invalidAndValidGradeGradeBook.json
  src/test/data/JsonGradeBookStorageTest/invalidGradeGradeBook.json
  src/test/data/JsonGradeBookStorageTest/notJsonFormatGradeBook.json
  src/test/data/JsonSerializableGradeBookTest/duplicateGradeGradeBook.json
  src/test/data/JsonSerializableGradeBookTest/invalidGradeGradeBook.json
  src/test/data/JsonSerializableGradeBookTest/typicalGradeGradeBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/gradecommands/AddGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/gradecommands/DeleteGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/gradecommands/EditGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/gradecommands/ListGradeCommandTest.java
  src/test/java/seedu/address/logic/parser/gradeparser/AddGradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/gradeparser/DeleteGradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/gradeparser/EditGradeCommandParserTest.java
  src/test/java/seedu/address/model/grade/GradeBookTest.java
  src/test/java/seedu/address/model/grade/GradeEnumTest.java
  src/test/java/seedu/address/model/grade/GradeListTest.java
  src/test/java/seedu/address/model/grade/GradeTest.java
  src/test/java/seedu/address/model/grade/GradedItemTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGradeTest.java
  src/test/java/seedu/address/storage/JsonGradeBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableGradeBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditGradeDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalGrades.java
Labels: priority.High, type.Bug, type.Task

#293 Branch budget UI
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/budgetcommands/AddBudgetCommand.java
  src/main/java/seedu/address/logic/commands/budgetcommands/DeleteBudgetCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TutorBook.java
  src/main/java/seedu/address/model/budget/GetAppointmentCost.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/budgetpanel/BudgetCard.java
  src/main/java/seedu/address/ui/budgetpanel/BudgetListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TabStyle.css
  src/main/resources/view/budgetpanel/BudgetCard.fxml
  src/main/resources/view/budgetpanel/BudgetListPanel.fxml
  src/test/java/seedu/address/logic/commands/tutorcommands/AddCommandTest.java
Labels: bug, severity.Low

#292 Edit error message for email
  src/main/java/seedu/address/model/tutor/Email.java
Labels: type.Bug

#295 Fix TabPane Tab's Width and BudgetCard styling issue
  .gitignore
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/budgetpanel/BudgetCard.java
  src/main/java/seedu/address/ui/budgetpanel/BudgetListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TabStyle.css
  src/main/resources/view/budgetpanel/BudgetCard.fxml
Labels: severity.Low, type.Bug

#290 Improve Ui and Tabs Switching Commands
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/ViewAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/budgetcommands/AddBudgetCommand.java
  src/main/java/seedu/address/logic/commands/budgetcommands/DeleteBudgetCommand.java
  src/main/java/seedu/address/logic/commands/budgetcommands/EditBudgetCommand.java
  src/main/java/seedu/address/logic/commands/budgetcommands/ViewBudgetCommand.java
  src/main/java/seedu/address/logic/commands/gradecommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradecommands/DeleteGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradecommands/EditGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradecommands/ListGradeCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/EditReminderCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/ListReminderCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/ListScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/ViewScheduleCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/MainWindow.fxml
Labels: severity.Low, type.Bug

#291 edited delete_tutor, add_note, list_note, delete_tutor
  docs/UserGuide.md
Labels: type.Bug

#296 First version of PPP
  docs/team/yutingzou.md
Labels: documentation, priority.Medium

#303 Improve grading system
  src/main/java/seedu/address/logic/commands/gradecommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradecommands/EditGradeCommand.java
  src/main/java/seedu/address/model/grade/GradeEnum.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonGradeBookStorageTest/invalidAndValidGradeGradeBook.json
  src/test/data/JsonSerializableGradeBookTest/duplicateGradeGradeBook.json
  src/test/data/JsonSerializableGradeBookTest/typicalGradeGradeBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/grade/GradeEnumTest.java
  src/test/java/seedu/address/testutil/GradeBookBuilder.java
  src/test/java/seedu/address/testutil/GradeBuilder.java
  src/test/java/seedu/address/testutil/TypicalGrades.java
Labels: priority.High, type.Bug, type.Enhancement

#298 Edited Model class diagram and DG
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation

#302 Bug fixes
  src/main/java/seedu/address/commons/exportutils/ExportUtils.java
  src/main/java/seedu/address/model/subject/SubjectName.java
  src/main/java/seedu/address/model/subject/SubjectQualification.java
  src/main/java/seedu/address/model/tutor/Gender.java
  src/main/java/seedu/address/ui/TutorCard.java
  src/main/resources/view/TutorListCard.fxml
Labels: type.Bug

#301 Fix to budget GUI display
  docs/UserGuide.md
  docs/images/ug-images/Budget_2.PNG
  src/main/java/seedu/address/ui/budgetpanel/BudgetListPanel.java
Labels: bug, priority.Medium

#300 Updated PPP (First version)
  docs/team/jared98lyj.md
Labels: documentation, priority.Low

#304 Bug fix for Appointment, Schedule and Reminder
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/DateTimeValidationUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/EditReminderCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedulecommands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/scheduleparser/EditScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/main/java/seedu/address/model/event/DateRangePredicate.java
  src/main/java/seedu/address/model/event/DateTimeClashPredicate.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventModel.java
  src/main/java/seedu/address/model/event/EventTracker.java
  src/main/java/seedu/address/storage/JsonSerializableAppointmentBook.java
  src/main/java/seedu/address/storage/JsonSerializableScheduleTracker.java
  src/main/java/seedu/address/ui/timetablepanel/TimeTablePanel.java
  src/test/java/seedu/address/logic/commands/tutorcommands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/appointmentparser/ViewAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/testutil/TypicalDates.java
Labels: severity.Medium, type.Bug

#305 Added PPP, made minor edits to DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/Winniehyx.md
Labels: documentation

#309 Update draft PPP
  docs/team/glatiuden.md
Labels: documentation, priority.Medium, type.Task

#307 Update DG
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#312 Fix bug where clear error message is not given if not all subject fields are given in edit_tutor
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/tutorparser/EditCommandParser.java
  src/main/java/seedu/address/model/subject/SubjectList.java
Labels: severity.Medium, type.Bug

#315 Update user guide to fix composed filter rule list spacing
  docs/UserGuide.md
Labels: priority.Low, type.Bug

#314 Fix qualification parsing to reject blank input and update error message
  src/main/java/seedu/address/model/subject/SubjectQualification.java
Labels: priority.Low, type.Bug

#313 Update DG for Budget
  docs/DeveloperGuide.md
Labels: documentation, priority.Low

#316 Fix bugs related to filter feature parsing and functionality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/commands/filtercommands/AddAppointmentFilterCommand.java
  src/main/java/seedu/address/logic/commands/filtercommands/AddPersonFilterCommand.java
  src/main/java/seedu/address/logic/commands/filtercommands/DeleteAppointmentFilterCommand.java
  src/main/java/seedu/address/logic/commands/filtercommands/DeletePersonFilterCommand.java
  src/main/java/seedu/address/logic/parser/filterparser/AddAppointmentFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/filterparser/AddPersonFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/filterparser/DeleteAppointmentFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/filterparser/DeletePersonFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/filterparser/FilterParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/filter/AppointmentFilter.java
  src/main/java/seedu/address/model/filter/SubjectQualificationFilter.java
  src/main/java/seedu/address/model/filter/TutorFilter.java
  src/test/java/seedu/address/logic/commands/filtercommands/DeleteTutorFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/AddCommandTest.java
  src/test/java/seedu/address/model/filter/TutorFilterTest.java
Labels: severity.High, type.Bug

#317 Add Reminder, Schedule and Timetable Implementation to DG
  docs/DeveloperGuide.md
  docs/diagrams/reminder/ReminderActivityDiagram.puml
  docs/diagrams/reminder/ReminderSequenceDiagram.puml
  docs/diagrams/schedule/ScheduleActivityDiagram.puml
  docs/diagrams/schedule/ScheduleSequenceDiagram.puml
  docs/diagrams/timetable/TimetableWindowActivityDiagram.puml
  docs/diagrams/timetable/TimetableWindowSequenceDiagram.puml
  docs/images/reminder/ReminderActivityDiagram.png
  docs/images/reminder/ReminderSequenceDiagram.png
  docs/images/schedule/ScheduleActivityDiagram.png
  docs/images/schedule/ScheduleSequenceDiagram.png
  docs/images/timetable/TimetableWindowActivityDiagram.png
  docs/images/timetable/TimetableWindowSequenceDiagram.png
Labels: documentation, priority.High, type.Task

#318 Refactor and improve code quality of filter feature
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/common/Description.java
  src/main/java/seedu/address/model/common/Title.java
  src/main/java/seedu/address/model/filter/AppointmentFilter.java
  src/main/java/seedu/address/model/filter/ExclusiveFilterSet.java
  src/main/java/seedu/address/model/filter/FilterSet.java
  src/main/java/seedu/address/model/filter/InclusiveFilterSet.java
  src/main/java/seedu/address/model/filter/TutorFilter.java
  src/main/java/seedu/address/model/grade/Grade.java
  src/main/java/seedu/address/model/grade/GradedItem.java
  src/main/java/seedu/address/model/subject/SubjectExperience.java
  src/main/java/seedu/address/model/subject/SubjectLevel.java
  src/main/java/seedu/address/model/subject/SubjectName.java
  src/main/java/seedu/address/model/subject/SubjectQualification.java
  src/main/java/seedu/address/model/subject/SubjectRate.java
  src/main/java/seedu/address/model/subject/TutorSubject.java
  src/main/java/seedu/address/model/tag/Filterable.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tutor/Address.java
  src/main/java/seedu/address/model/tutor/Email.java
  src/main/java/seedu/address/model/tutor/Gender.java
  src/main/java/seedu/address/model/tutor/Name.java
  src/main/java/seedu/address/model/tutor/Notes.java
  src/main/java/seedu/address/model/tutor/Phone.java
  src/test/java/seedu/address/model/tutor/NotesTest.java
Labels: priority.Medium, type.Enhancement

#319 Add Reminder & Event Unit Test
  src/main/java/seedu/address/commons/util/DateTimeValidationUtil.java
  src/main/java/seedu/address/logic/commands/eventcommands/ViewTimeTableCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/AddReminderCommand.java
  src/main/java/seedu/address/logic/parser/eventparser/ViewTimeTableCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedReminder.java
  src/test/data/JsonReminderTrackerStorageTest/invalidAndValidReminderTracker.json
  src/test/data/JsonReminderTrackerStorageTest/invalidReminderTracker.json
  src/test/data/JsonReminderTrackerStorageTest/notJsonFormatReminderTracker.json
  src/test/data/JsonSerializableReminderTrackerTest/duplicateReminderTracker.json
  src/test/data/JsonSerializableReminderTrackerTest/invalidReminderTracker.json
  src/test/data/JsonSerializableReminderTrackerTest/typicalReminderTracker.json
  src/test/data/JsonSerializableScheduleTrackerTest/typicalScheduleTracker.json
  src/test/java/seedu/address/commons/util/DateTimeValidationUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/eventcommands/ViewEventCommandTest.java
  src/test/java/seedu/address/logic/commands/eventcommands/ViewTimeTableCommandTest.java
  src/test/java/seedu/address/logic/commands/remindercommands/AddReminderCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/remindercommands/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/remindercommands/DeleteReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/remindercommands/EditReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/remindercommands/EditReminderDescriptorTest.java
  src/test/java/seedu/address/logic/commands/remindercommands/ListReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/schedulecommands/AddScheduleCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/schedulecommands/EditScheduleDescriptorTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TutorTrackerParserTest.java
  src/test/java/seedu/address/logic/parser/eventparser/ViewEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/eventparser/ViewTimeTableCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reminderparser/AddReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reminderparser/DeleteReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reminderparser/EditReminderCommandParserTest.java
  src/test/java/seedu/address/model/reminder/ReminderDateTest.java
  src/test/java/seedu/address/model/reminder/ReminderListTest.java
  src/test/java/seedu/address/model/reminder/ReminderTest.java
  src/test/java/seedu/address/model/reminder/ReminderTrackerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedReminderTest.java
  src/test/java/seedu/address/storage/JsonReminderTrackerStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableReminderTrackerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditReminderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ReminderBuilder.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalReminders.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.Medium, type.Bug, type.Task

#322 Update Kingsley Project Portfolio Page to list features added
  docs/team/kingsleykuan.md
Labels: documentation, priority.Medium

#323 Rename winniehyx.md
  docs/AboutUs.md
  docs/team/winniehyx.md
Labels: documentation

#325 Bug fix and edit DG for notes UML
  docs/DeveloperGuide.md
  docs/diagrams/notes/NotesActivityDiagram.puml
  docs/diagrams/notes/NotesSequenceDiagram.puml
  docs/images/notes/NotesActivityDiagram.png
  docs/images/notes/NotesSequenceDiagram.png
  src/main/java/seedu/address/model/subject/SubjectExperience.java
  src/main/java/seedu/address/model/subject/SubjectRate.java
Labels: type.Bug

#327 Add unit tests for filter feature (WIP)
  src/main/java/seedu/address/model/filter/EmailFilter.java
  src/test/java/seedu/address/model/filter/AddressFilterTest.java
  src/test/java/seedu/address/model/filter/AppointmentDateTimeFilterTest.java
  src/test/java/seedu/address/model/filter/EmailFilterTest.java
  src/test/java/seedu/address/model/filter/GenderFilterTest.java
  src/test/java/seedu/address/model/filter/NameFilterTest.java
  src/test/java/seedu/address/model/filter/PhoneFilterTest.java
  src/test/java/seedu/address/model/filter/SubjectExperienceFilterTest.java
  src/test/java/seedu/address/model/filter/SubjectLevelFilterTest.java
  src/test/java/seedu/address/model/filter/SubjectNameFilterTest.java
  src/test/java/seedu/address/model/filter/SubjectQualificationFilterTest.java
  src/test/java/seedu/address/model/filter/SubjectRateFilterTest.java
Labels: priority.Medium, type.Enhancement

#331 Fix SubjectExperienceFilterTest to match new length limit
  src/test/java/seedu/address/model/filter/SubjectExperienceFilterTest.java
Labels: severity.High, type.Bug

#329 Update DG - GradeBook implementation
  docs/DeveloperGuide.md
  docs/diagrams/grade/GradeActivityDiagram.puml
  docs/diagrams/grade/GradeSequenceDiagram.puml
  docs/images/grade/GradeActivityDiagram.png
  docs/images/grade/GradeSequenceDiagram.png
Labels: documentation, priority.High

#333 Fix bug and update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GradeClassDiagram.puml
  docs/images/grade/GradeClassDiagram.png
  docs/team/yutingzou.md
  src/main/java/seedu/address/model/grade/Grade.java
  src/main/java/seedu/address/model/grade/GradeEnum.java
  src/main/java/seedu/address/model/grade/GradedItem.java
  src/main/java/seedu/address/storage/JsonAdaptedGrade.java
  src/test/java/seedu/address/model/grade/GradeTest.java
  src/test/java/seedu/address/model/grade/GradedItemTest.java
Labels: bug, enhancement, priority.High

#336 Add unit tests for subject classes
  src/test/java/seedu/address/model/subject/SubjectExperienceTest.java
  src/test/java/seedu/address/model/subject/SubjectLevelTest.java
  src/test/java/seedu/address/model/subject/SubjectNameTest.java
  src/test/java/seedu/address/model/subject/SubjectQualificationTest.java
  src/test/java/seedu/address/model/subject/SubjectRateTest.java
Labels: priority.Medium, type.Enhancement

#335 Add remaining tests for filter feature
  src/test/java/seedu/address/logic/commands/filtercommands/AddAppointmentFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/AddPersonFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/AddTutorFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/DeleteAppointmentFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/DeletePersonFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/filtercommands/DeleteTutorFilterCommandTest.java
  src/test/java/seedu/address/logic/parser/filterparser/AddAppointmentFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/filterparser/AddPersonFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/filterparser/AddTutorFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/filterparser/DeleteAppointmentFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/filterparser/DeletePersonFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/filterparser/DeleteTutorFilterCommandParserTest.java
  src/test/java/seedu/address/model/filter/AppointmentFilterTest.java
  src/test/java/seedu/address/model/filter/ExclusiveFilterSetTest.java
  src/test/java/seedu/address/model/filter/InclusiveFilterSetTest.java
  src/test/java/seedu/address/model/filter/TutorFilterTest.java
  src/test/java/seedu/address/testutil/TypicalFilters.java
Labels: priority.Medium, type.Enhancement

#343 Fixed edit_tutor bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/tutorcommands/EditCommand.java
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/tutorcommands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorcommands/EditCommandTest.java
Labels: bug, priority.Medium

#344 Fix Grade bugs and improve documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/grade/GradeActivityDiagram.puml
  docs/images/grade/GradeActivityDiagram_updated.png
  docs/images/ug-images/Grades_updated.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/gradeparser/AddGradeCommandParser.java
  src/main/java/seedu/address/logic/parser/gradeparser/EditGradeCommandParser.java
  src/main/java/seedu/address/model/grade/Grade.java
  src/main/java/seedu/address/model/grade/GradedItem.java
  src/main/java/seedu/address/storage/JsonAdaptedGrade.java
  src/main/java/seedu/address/ui/GradeCard.java
  src/main/java/seedu/address/ui/TutorCard.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/gradeparser/AddGradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/gradeparser/EditGradeCommandParserTest.java
  src/test/java/seedu/address/model/grade/GradeTest.java
  src/test/java/seedu/address/model/grade/GradedItemTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGradeTest.java
Labels: bug, documentation, enhancement, severity.High

#347 Update developer guide for filter feature
  docs/DeveloperGuide.md
  docs/diagrams/filter/FilterActivityDiagram.puml
  docs/diagrams/filter/FilterClassDiagram.puml
  docs/diagrams/filter/FilterSequenceDiagram.puml
  docs/images/filter/FilterActivityDiagram.png
  docs/images/filter/FilterClassDiagram.png
  docs/images/filter/FilterSequenceDiagram.png
Labels: priority.Medium, type.Enhancement

#348 Edit user guide and PPP
  docs/UserGuide.md
  docs/team/winniehyx.md
Labels: documentation

#351 Update DG class diagram for budget and appointment
  docs/DeveloperGuide.md
  docs/diagrams/appointment/AddAppointmentActivityDiagram.puml
  docs/diagrams/appointment/AppointmentSequenceDiagram.puml
  docs/diagrams/budget/BudgetActivityDiagaram.puml
  docs/diagrams/budget/BudgetSequenceDiagram.puml
  docs/images/appointment/appointmentActivity.png
  docs/images/appointment/appointmentSequence.png
  docs/images/budget/budgetActivity.png
  docs/images/budget/budgetSequence.png
Labels: documentation, priority.Medium

#349 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/yutingzou.md
Labels: documentation, enhancement, priority.High

#357 Update developer guide to include design considerations for filter feature
  docs/DeveloperGuide.md
Labels: documentation

#356 Update PPP
  docs/team/kingsleykuan.md
Labels: documentation, priority.Medium, type.Enhancement

#362 Update list grades
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/grade/GradeSequenceDiagram.puml
  docs/images/grade/GradeSequenceDiagram_updated.png
  docs/images/ug-images/Budget_updated.png
  docs/images/ug-images/Filters_updated.png
  docs/images/ug-images/Grades_updated.png
  docs/images/ug-images/Reminder_updated.png
Labels: documentation
